blank_issues_enabled: false
contact_links:
  - name: NeurIPS 2026 Anonymous Submission
    url: https://openreview.net/
    about: This is an anonymous code release for review. Please direct questions through OpenReview during the review period.
